### ISSUE TITLE
calibrating state doesn't honour night simulator

### ISSUE THREAD

**Issue by AnthonyHorton** [wtgee/huntsman-pocs#114]
When attempting to test Huntsman during the day using the night simulator it gets stuck in the calibrating state waiting for real night time.

When creating a `POCS` instance with `simulator = ['night', ...]` it ensures that the darkness check `POCS.is_dark()` always return true, however the Huntsman calibrating state checks the Sun altitude directly without also checking `is_dark()`. Consequently Huntsman gets stuck in the calibrating state waiting for real astronomical twilight.

**Comment by wtgee** [comment]
Ah, yes, getting stuck here:

https://github.com/AstroHuntsman/huntsman-pocs/blob/develop/states/huntsman/calibrating.py#L39-L41
