### ISSUE TITLE
HuntsmanObservatory doesn't focus remote cameras

### ISSUE THREAD

**Issue by AnthonyHorton** [wtgee/huntsman-pocs#115]
HuntsmanObservatory skips autofocus on all the distributed cameras because it thinks they don't have a focuser.

**Comment by wtgee** [comment]
Do you know if this is this a configuration problem or a code problem?

**Comment by AnthonyHorton** [comment]
@wtgee It's a code problem. `pocs.observatory.Observatory.autofocus_cameras()` checks the `.focuser.is_connected` attribute of the cameras to decided if they can be focused, but the client side Pyro `Camera` class has no `.focuser` attribute. I need to add a proxy focuser to it to enable access to the remote camera's focuser's properties and methods.
