### ISSUE TITLE
Not transitioning from ready state to calibrating (?)

### ISSUE THREAD

**Issue by fergusL** [wtgee/huntsman-pocs#124]
When starting up huntsman before twilight, it seems we never make the transition from ready into calibrating (to take flats). Instead POCS ends up waiting until the sun is below -18 degree and then tries to take flats and concludes it is too dark.
This is probably due to a change to the `Observatory.is_dark()` method from POCS, where it now has a kwarg for the horizon level. By default this is `observe` which corresponds to -18 degree sun altitude. The two other options are `flat` and `focus`. This `is_dark()` method gets called by the `POCS.is_safe()` method so there should just be a `is_safe()` or `is_dark()` call somewhere that needs to have `horizon='flat'` passed to it. Then POCS should transition from the ready state to the calibrating state as desired.

**Comment by lspitler** [comment]
@wtgee , @fergusL mentioned this might be a simple `horizon='flat'` fix somewhere. And that you might be able to do this very quickly. Is this something you can check out really quick?
