### ISSUE TITLE
add auto sshfs mount to camera server

### ISSUE THREAD

**Issue by lspitler** [wtgee/huntsman-pocs#132]
Don't want to do manual step:
`python /huntsman-pocs/scripts/auto_sshfs_mount.py`

Instead should:
"The camera code doesn't know about the network mounts. It will just try to write to the Pi's filesystem wherever you tell it to. 
The mounting/demounting of the sshfs mount should really go into the camera server code.
Instead of being a separate manual step."

@AnthonyHorton @danjampro does this just go here: 
https://github.com/AstroHuntsman/huntsman-pocs/blob/develop/scripts/pyro_camera_server.py
?

**Comment by danjampro** [comment]
Change implemented and tested
