### ISSUE TITLE
Remove explict list in huntsman-run-test

### ISSUE THREAD

**Issue by wtgee** [wtgee/huntsman-pocs#166]
We still need it for now. You fixed this in the `listify()` in `panoptes-utils` but `pocs.core.POCS.wait_for_events()` still uses the version from `pocs.utils`, which can't handle `dict_values` objects. Once POCS switches to `panoptes-utils` we can just pass the `dict` here.

_Originally posted by @AnthonyHorton in https://github.com/AstroHuntsman/huntsman-pocs/pull/165_

Depends on #167

**Comment by AnthonyHorton** [comment]
`list()` is here: https://github.com/AnthonyHorton/huntsman-pocs/blob/4e57f260a255c36b2d6d88826202fd132d0cd160/states/huntsman/calibrating.py#L109

**Comment by wtgee** [comment]
Closed by #167
