### ISSUE TITLE
Config Server Updates - panoptes-utils

### ISSUE THREAD

**Issue by wtgee** [wtgee/huntsman-pocs#171]
Reconcile the differences between `huntsman/utils/config.py` and the config server that is located in https://github.com/panoptes/panoptes-utils.

Part of #167 
Related to #137

**Comment by lspitler** [comment]
See discussion here: https://aao-org.slack.com/archives/GKB3AFZQT/p1581908224300900

**Comment by lspitler** [comment]
Fixed with #196
