### ISSUE TITLE
Flat field code needs updating

### ISSUE THREAD

**Issue by danjampro** [wtgee/huntsman-pocs#198]
- Change default initial exposure time to 5s
- Increase max exposure time to 120s
- Reduce min exposure time to 0.5s
- Decrease required number of good flat fields to 5 AND/OR
- Reduce time between exposures
- Have a timeout in the loop that waits for exposures to complete

**Comment by wtgee** [comment]
Let's identify what could be set in the config vs not.  Seems like the first 4 are configurable.  The timeout on the 6th is configurable.
