### ISSUE TITLE
Arch not correct in ASI lib install script

### ISSUE THREAD

**Issue by danjampro** [wtgee/huntsman-pocs#221]
https://github.com/AstroHuntsman/huntsman-pocs/blob/d0e9b9e2cc1bdd7c6d6813b9c9fddd974be28e19/scripts/install_asi_libs.sh#L12

The script produces ARCH=armv7l but we need armv7 to install the ZWO software.

**Comment by AnthonyHorton** [comment]
Added wrinkle, when we reimage the Pi's with the 64-bit Ubuntu image we should probably be using the armv8 library.
