### ISSUE TITLE
list of possibly useful stale branches that can be revived someday

### ISSUE THREAD

**Issue by lspitler** [wtgee/huntsman-pocs#229]
- https://github.com/AstroHuntsman/huntsman-pocs/pull/48
- https://github.com/AstroHuntsman/huntsman-pocs/pull/50
- https://github.com/AstroHuntsman/huntsman-pocs/pull/70

**Comment by AnthonyHorton** [comment]
Probably not going to need the Hue lighting code at any point, and I'm not sure the weather stuff is needed, but it would be good to resurrect the ToO stuff at some point. Not much point in doing so until we're in routine, automated operations though.

**Comment by wtgee** [comment]
I think we should address he ToO stuff as a larger part of scheduling in general.
