### ISSUE TITLE
open / close dome states in POCS

### ISSUE THREAD

**Issue by lspitler** [wtgee/huntsman-pocs#237]
Various things on this front:

- [ ] reliability of dome info query #236 
- [ ] misc task related to musca #60 
- [ ] design states for opening the dome and closing when e.g. weather is bad

**Comment by lspitler** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [POCS dome shutter control](https://trello.com/c/6GJsZa8w/178-pocs-dome-shutter-control)

**Comment by danjampro** [comment]
Closed by #245
