### ISSUE TITLE
Going to `ready` state while it is not safe to open the dome.

### ISSUE THREAD

**Issue by bazkiaei** [wtgee/huntsman-pocs#318]
`pocs` goes to `sleeping` state when it is not safe to observe, e.g. there is no weather data available. But it just goes back to `ready` state and opens the dome.
@AnthonyHorton believes there might be some bugs related to weather safety checks, also `pocs.reset_observing_run()` in the `sleeping` state should handle it but it does not.

**Comment by danjampro** [comment]
@bazkiaei I believe the "ready" state is tagged as "always_safe", so this is expected behaviour. This looks related to #299 ?
