### ISSUE TITLE
The ipython tab bug

### ISSUE THREAD

**Issue by Physarah** [wtgee/huntsman-pocs#324]
When using Ipython inside docker containers - tab causes the ipython session to crash. Jedi needs to be downgraded inside all containers that we work in, to ensure this doesn't happen. 

Is there a way to set a downgraded version of jedi in a container as default?

**Comment by danjampro** [comment]
Should fix itself (via docker CI) if and when the jedi autocomplete gets fixed.

**Comment by danjampro** [comment]
This appears to have fixed it self and autocomplete is working again.
