### ISSUE TITLE
No record found for weather

### ISSUE THREAD

**Issue by Physarah** [wtgee/huntsman-pocs#325]
Weather needs to be run as simulator until pocs can find the weather.db file. I think this has something to do with it not being able to find it outside of docker? @wtgee is working on this currently.

**Comment by wtgee** [comment]
Ideally this was solved by #322 but in our initial testing that didn't seem to be the case.

The problem concerns which volumes are shared in the `docker-compose` file.  Basically we need to make the host `json_store` (or whatever we rename it via the config) available inside the container.

#327 is a similar volume configuration issue.
