### ISSUE TITLE
Filter None requested by observation

### ISSUE THREAD

**Issue by Physarah** [wtgee/huntsman-pocs#326]
"Filter None requested by observation but ZWO Filter Wheel (8) [Camera: 192.168.80.XXX] is missing that filter, using luminance."

Didn't seem to stop pocs, it just went to the next state. This is a known bug, @AnthonyHorton knows more about this

**Comment by danjampro** [comment]
I believe this is a problem with the flat fielding. It does not affect anything serious, but should be addressed in the upcoming flat field revamp.

**Comment by danjampro** [comment]
@danjampro to silence warning in `POCS`

**Comment by danjampro** [comment]
See https://github.com/panoptes/POCS/pull/1072

**Comment by danjampro** [comment]
This has now been fixed.
