### ISSUE TITLE
Can't find archive directory on clean up 

### ISSUE THREAD

**Issue by Physarah** [wtgee/huntsman-pocs#327]
"Problem with cleanup: [Errno 2] No such file or directory: '/var/huntsman/archive'"

A warning "Problem with cleanup: [Errno 2] No such file or directory: '/var/huntsman/archive'" occurred when pocs started to shut everything down. '/var/huntsman/archive' does exists. Note sure why it couldn't find it? @danjampro you might know more about this? Low priority for now I think.

**Comment by wtgee** [comment]
As mentioned in #325 , this is just a volume configuration issue inside the `docker-compose` file.

**Comment by danjampro** [comment]
I fixed this here: https://github.com/AstroHuntsman/huntsman-pocs/commit/58d312921c2e545b1576ef78b2816f72f610df5b
