### ISSUE TITLE
Skip dithering state if not a dithered observation.

### ISSUE THREAD

**Issue by wtgee** [wtgee/huntsman-pocs#99]
Targets were performing minor slews in the `dithering` state even if a target has the `no_dither: True` option. This was causing problems with the autoguider.

Should skip the dither state entirely if it is not a `DitheredObservation`. This logic is in the `analyzing` state.

**Comment by AnthonyHorton** [comment]
This looks to my uninformed eyes like an easy one to fix. Is it just a case of replacing `pocs.next_state = 'dithering'` with 
```
if isinstance(observation, DitheredObservation):
    pocs.next_state = 'dithering'
else:
    pocs.next_state = 'scheduling'
```
in `analyzing.py`?  Happy to dive in a do it if that's all it is.
